name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgeos-dev libffi-dev libssl-dev

      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Docker Compose (Python package)
        run: |
          python -m pip install "docker-compose>=2.20.0,<3.0"

      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
